#
# $Id: Makefile,v 1.5 2001/02/15 01:09:57 mdb Exp $

ROOT = ../../..

SRCS = \
	ConfigUtil.java \
	DefaultLogProvider.java \
	Log.java \
	LogProvider.java \
	PropertiesUtil.java \
	StringUtil.java \

include $(ROOT)/build/Makefile.java
