#
# $Id: Makefile,v 1.4 2000/12/06 03:21:59 mdb Exp $

ROOT = ../../..

SRCS = \
	DefaultLogProvider.java \
	Log.java \
	LogProvider.java \
	PropertiesUtil.java \
	StringUtil.java \

include $(ROOT)/build/Makefile.java
