#
# $Id: Makefile,v 1.6 2001/03/01 18:47:01 mdb Exp $

ROOT = ../../..

SRCS = \
	ConfigUtil.java \
	DefaultLogProvider.java \
	IntMap.java \
	IntIntMap.java \
	Log.java \
	LogProvider.java \
	PropertiesUtil.java \
	StringUtil.java \

include $(ROOT)/build/Makefile.java
