// generated 2002/12/1 21:56:20 PST by mdb@baltic.(none)
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// /usr/local/bin/glade-- --gnome2 lookuplet.glade
// for gtk 2.0.9 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ./src/about.cc

#include "config.h"
#include "about_glade.hh"
#include <vector>

const char * const about_authors[] = 
{       "Michael Bayne <mdb@samskivert.com>", 0
};

about_glade::about_glade(
) : Gnome::UI::About(PACKAGE, VERSION, "(C) 2001-2002 Michael Bayne", about_authors, about_authors, "This GNOME applet provides a simple means by which web and other queries can be launched with minimal typing.\n"
		"-\n"
		"This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.")
{  
   
   Gnome::UI::About *about = this;
   about->show();
}

about_glade::~about_glade()
{  
}
