// generated 2002/12/1 19:52:51 PST by mdb@baltic.(none)
// using glademm V1.1.0c
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /export/home/mdb/projects/lookuplet/lookuplet.glade
// for gtk 2.0.9 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ./src/about.hh and./src/about.cc

#ifndef _ABOUT_GLADE_HH
#  define _ABOUT_GLADE_HH

#include <libgnomeuimm/about.h>

class about_glade : public Gnome::UI::About
{  
protected:
        
        
        about_glade();
        
        ~about_glade();
};
#endif
