// generated 2002/12/1 21:56:20 PST by mdb@baltic.(none)
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// /usr/local/bin/glade-- --gnome2 lookuplet.glade
// for gtk 2.0.9 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ./src/binding.hh and./src/binding.cc

#ifndef _BINDING_GLADE_HH
#  define _BINDING_GLADE_HH

#include <gtkmm/dialog.h>
#include <gtkmm/entry.h>
#include <gtkmm/optionmenu.h>

class binding_glade : public Gtk::Dialog
{  
protected:
        
        class Gtk::Entry *_key;
        class Gtk::Entry *_name;
        class Gtk::OptionMenu *_type;
        class Gtk::Entry *_argument;
        
        binding_glade();
        
        ~binding_glade();
private:
        virtual void on_ok_clicked() = 0;
        virtual void on_cancel_clicked() = 0;
        virtual bool on_key_key_press_event(GdkEventKey *ev) = 0;
};
#endif
