// generated 2002/12/1 21:56:20 PST by mdb@baltic.(none)
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// /usr/local/bin/glade-- --gnome2 lookuplet.glade
// for gtk 2.0.9 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ./src/lookuplet.hh and./src/lookuplet.cc

#ifndef _LOOKUPLET_GLADE_HH
#  define _LOOKUPLET_GLADE_HH

#include <gtkmm/window.h>
#include <gtkmm/entry.h>

class lookuplet_glade : public Gtk::Window
{  
protected:
        
        class Gtk::Entry *_query;
        
        lookuplet_glade();
        
        ~lookuplet_glade();
private:
        virtual bool on_query_key_press_event(GdkEventKey *ev) = 0;
        virtual void on_prefs_clicked() = 0;
};
#endif
