// generated 2002/12/1 21:56:20 PST by mdb@baltic.(none)
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// /usr/local/bin/glade-- --gnome2 lookuplet.glade
// for gtk 2.0.9 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ./src/lookuplet.cc

#include "config.h"
#include "lookuplet_glade.hh"
#include <gtkmm/label.h>
#include <gtkmm/button.h>
#include <gtkmm/box.h>

lookuplet_glade::lookuplet_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  
   
   Gtk::Window *lookuplet = this;
   Gtk::Label *qlabel = manage(new class Gtk::Label("Query"));
   _query = manage(new class Gtk::Entry());
   
   Gtk::Button *prefs = manage(new class Gtk::Button("Prefs"));
   Gtk::HBox *mainbox = manage(new class Gtk::HBox(false, 5));
   qlabel->set_alignment(0.5,0.5);
   qlabel->set_padding(0,0);
   qlabel->set_justify(Gtk::JUSTIFY_CENTER);
   qlabel->set_line_wrap(false);
   _query->set_flags(Gtk::CAN_FOCUS);
   _query->set_editable(true);
   _query->set_text("");
   prefs->set_relief(Gtk::RELIEF_NORMAL);
   mainbox->set_border_width(5);
   mainbox->pack_start(*qlabel, Gtk::PACK_SHRINK, 0);
   mainbox->pack_start(*_query);
   mainbox->pack_start(*prefs, Gtk::PACK_SHRINK, 0);
   lookuplet->set_title("lookuplet");
   lookuplet->set_modal(false);
   lookuplet->property_window_position().set_value(Gtk::WIN_POS_NONE);
   lookuplet->set_resizable(true);
   lookuplet->add(*mainbox);
   qlabel->show();
   _query->show();
   prefs->show();
   mainbox->show();
   lookuplet->show();
   _query->signal_key_press_event().connect(SigC::slot(*this, &lookuplet_glade::on_query_key_press_event));
   prefs->signal_clicked().connect(SigC::slot(*this, &lookuplet_glade::on_prefs_clicked));
}

lookuplet_glade::~lookuplet_glade()
{  
}
