// generated 2002/12/1 21:56:20 PST by mdb@baltic.(none)
// using glademm V1.1.3c_cvs
//
// DO NOT EDIT THIS FILE ! It was created using
// /usr/local/bin/glade-- --gnome2 lookuplet.glade
// for gtk 2.0.9 and gtkmm 2.0.0
//
// Please modify the corresponding derived classes in ./src/properties.hh and./src/properties.cc

#ifndef _PROPERTIES_GLADE_HH
#  define _PROPERTIES_GLADE_HH

#include <gtkmm/window.h>
#include <gtkmm/treeview.h>

class properties_glade : public Gtk::Window
{  
protected:
        
        class Gtk::TreeView *_bindings;
        
        properties_glade();
        
        ~properties_glade();
private:
        virtual void on_delete_clicked() = 0;
        virtual void on_edit_clicked() = 0;
        virtual void on_add_clicked() = 0;
        virtual void on_close_clicked() = 0;
};
#endif
