#
# $Id: Makefile,v 1.1 2001/02/13 05:46:56 mdb Exp $

ROOT = ../../../..

SRCS = \
	Cursor.java \
	DataTransferError.java \
	FieldDescriptor.java \
	NoCurrentObjectError.java \
	NoPrimaryKeyError.java \
	SQLError.java \
	Session.java \
	SessionThread.java \
	Table.java \

include $(ROOT)/build/Makefile.java
