#
# $Id: Makefile,v 1.1 2000/11/08 06:42:57 mdb Exp $

ROOT = ../..

SRCS = \
	Category.java \
	CategoryMapping.java \
	Entry.java \
	Repository.java \
	RepositoryTest.java \
	Song.java \

include $(ROOT)/build/Makefile.java
