#
# $Id: Makefile,v 1.2 2001/03/02 02:08:50 mdb Exp $

ROOT = ../../../..

SRCS = \
	InvalidPasswordException.java \
	InvalidUsernameException.java \
	NoSuchUserException.java \
	User.java \
	UserExistsException.java \
	UserManager.java \
	UserRepository.java \
	UserUtil.java \

include $(ROOT)/build/Makefile.java
