#
# $Id: Makefile,v 1.1 2001/03/02 01:21:06 mdb Exp $

ROOT = ../../../..

SRCS = \
	InvalidUsernameException.java \
	User.java \
	UserExistsException.java \
	UserManager.java \
	UserRepository.java \

include $(ROOT)/build/Makefile.java
