#
# $Id: Makefile,v 1.1 2000/12/07 05:41:07 mdb Exp $

ROOT = ../../..

SRCS = \
	DimenInfo.java \
	GroupLayout.java \
	GroupLayoutTest.java \
	HGroupLayout.java \
	VGroupLayout.java \

include $(ROOT)/build/Makefile.java
