#
# $Id: Makefile,v 1.2 2001/02/13 20:00:28 mdb Exp $

ROOT = ../../..

SRCS = \
	ExceptionMap.java \
	FriendlyException.java \
	FriendlyServlet.java \
	Log.java \

include $(ROOT)/build/Makefile.java
