#
# $Id: Makefile,v 1.4 2001/03/01 21:06:22 mdb Exp $

ROOT = ../../..

SRCS = \
	DataValidationException.java \
	DispatcherServlet.java \
	DummyLogic.java \
	ExceptionMap.java \
	FormUtil.java \
	FriendlyException.java \
	Log.java \
	Logic.java \

include $(ROOT)/build/Makefile.java
