#
# $Id: Makefile,v 1.3 2001/02/15 01:44:34 mdb Exp $

ROOT = ../../..

SRCS = \
	ContextPopulator.java \
	DataValidationException.java \
	DispatcherServlet.java \
	DummyPopulator.java \
	ExceptionMap.java \
	FormUtil.java \
	FriendlyException.java \
	Log.java \

include $(ROOT)/build/Makefile.java
