#
# $Id: Makefile.local,v 1.1 2001/02/16 03:28:39 mdb Exp $
#
# Defines stuff common to this entire code tree

# this tells the build system where to install shared libraries built from
# this code tree
LIBDIR = $(ROOT)/../../lib/$(ARCH)

# where we put our zip and jar files
ARCHIVEDIR = $(ROOT)/../../lib

LOCAL_CLASSPATH += \
	$(shell ls $(ARCHIVEDIR)/*.jar) \

#	$(shell ls $(ARCHIVEDIR)/*.zip) \
