#
# $Id: Makefile,v 1.2 2000/10/30 22:21:11 mdb Exp $

ROOT = ../..

SRCS = \
	CDParanoiaRipper.java \
	ConversionProgressListener.java \
	ConvertException.java \
	Encoder.java \
	L3Encoder.java \
	RipTest.java \
	RipUtil.java \
	Ripper.java \

include $(ROOT)/build/Makefile.java
