#
# $Id: Makefile,v 1.1 2000/10/30 21:08:53 mdb Exp $

ROOT = ../..

SRCS = \
	CDParanoiaRipper.java \
	RipException.java \
	RipTest.java \
	RipUtil.java \
	Ripper.java \

include $(ROOT)/build/Makefile.java
