#
# $Id: Makefile,v 1.1 2000/12/10 07:02:09 mdb Exp $

ROOT = ../..

SRCS = \
	CDDBLookupPanel.java \
	CDDBUtil.java \
	CDInfoEditor.java \
	DetailTableModel.java \
	Importer.java \
	ImporterFrame.java \
	ImporterPanel.java \
	InsertCDPanel.java \
	RipPanel.java \

include $(ROOT)/build/Makefile.java
